CREATE TABLE T_AUTHORITY (
   ID  BIGINT NOT NULL,
   NAME VARCHAR(255),
   CREATED_BY VARCHAR(255) DEFAULT NULL,
   CREATED_DATE TIMESTAMP NOT NULL,
   MODIFIED_BY VARCHAR(255) DEFAULT NULL,
   MODIFIED_DATE TIMESTAMP DEFAULT NULL,
   PRIMARY KEY (ID)
);

ALTER TABLE IF EXISTS T_AUTHORITY ADD CONSTRAINT AUTHORITY_NAME UNIQUE (NAME);

CREATE TABLE T_USER (
   ID  BIGINT NOT NULL,
   ACCOUNT_EXPIRED BOOLEAN,
   ACCOUNT_LOCKED BOOLEAN,
   CREDENTIALS_EXPIRED BOOLEAN,
   ENABLED BOOLEAN,
   PASSWORD VARCHAR(255),
   USER_NAME VARCHAR(255),
   FIRST_NAME VARCHAR(50),
   LAST_NAME VARCHAR(50),
   EMAIL_ADDRESS VARCHAR(50),
   USER_TYPE VARCHAR(10),
   CREATED_BY VARCHAR(255) DEFAULT NULL,
   CREATED_DATE TIMESTAMP NOT NULL,
   MODIFIED_BY VARCHAR(255) DEFAULT NULL,
   MODIFIED_DATE TIMESTAMP DEFAULT NULL,
   PRIMARY KEY (ID)
);

ALTER TABLE IF EXISTS T_USER ADD CONSTRAINT USER_USER_NAME UNIQUE (USER_NAME);

CREATE TABLE T_USERS_AUTHORITIES (
   USER_ID BIGINT NOT NULL,
   AUTHORITY_ID BIGINT NOT NULL,
   PRIMARY KEY (USER_ID, AUTHORITY_ID)
);

ALTER TABLE IF EXISTS T_USERS_AUTHORITIES ADD CONSTRAINT USERS_AUTHORITIES_AUTHORITY
  FOREIGN KEY (AUTHORITY_ID) REFERENCES T_AUTHORITY;

ALTER TABLE IF EXISTS T_USERS_AUTHORITIES ADD CONSTRAINT USERS_AUTHORITIES_USER
  FOREIGN KEY (USER_ID) REFERENCES T_USER;
