INSERT INTO T_AUTHORITY(ID, NAME, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE) VALUES (1, 'USER_CREATE', 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO T_AUTHORITY(ID, NAME, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE) VALUES (2, 'USER_READ', 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO T_AUTHORITY(ID, NAME, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE) VALUES (3, 'USER_UPDATE', 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO T_AUTHORITY(ID, NAME, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE) VALUES (4, 'USER_DELETE', 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);

INSERT INTO T_AUTHORITY(ID, NAME, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE) VALUES (5, 'UNIT_CREATE', 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO T_AUTHORITY(ID, NAME, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE) VALUES (6, 'UNIT_READ', 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO T_AUTHORITY(ID, NAME, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE) VALUES (7, 'UNIT_UPDATE', 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);
INSERT INTO T_AUTHORITY(ID, NAME, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE) VALUES (8, 'UNIT_DELETE', 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP);